[phases.setup]
nixPkgs = ["python311", "pango", "harfbuzz", "fontconfig", "libGL", "glib", "gobject-introspection"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app"